name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
        - qt: 5.15.2
          arch: win64_msvc2019_64
          config: Release
          toolset: v142
          qtdirenvname: Qt5_DIR
        # Testing on Qt6 is disabled until https://bugreports.qt.io/browse/QTBUG-103611 is resolved
        #- qt: 6.2.4
        #  arch: win64_msvc2019_64
        #  config: Debug
        #  toolset: v142
        #  qtdirenvname: Qt6_DIR
    env:
      PACKAGE_NAME: libDOtherSide-windows-${{ matrix.arch }}-qt-${{ matrix.qt }}.zip

    steps:
    - uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-${{ matrix.arch }}-${{ matrix.qt }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        arch: ${{ matrix.arch }}
        version: ${{ matrix.qt }}

    - name: Compile
      shell: cmd
      run: |
        mkdir build
        cd build
        cmake -T"${{ matrix.toolset }}" -A x64 -DCMAKE_BUILD_TYPE=${{ matrix.config }} ..
        cmake --build . --config ${{ matrix.config }}

    - name: Compress artifacts
      shell: powershell
      run: |
        cd build
        cd lib
        cd Release
        Compress-Archive . release.zip
        ls

    - name: Test
      shell: cmd
      run: |
        set QT_PLUGIN_PATH=%${{ matrix.qtdirenvname }}%/plugins
        set QML2_IMPORT_PATH=%${{ matrix.qtdirenvname }}%/qml
        "build\test\${{ matrix.config }}\TestDynamicQObject.exe"

    - name: Upload binaries
      uses: actions/upload-artifact@master
      with:
        name: ${{ env.PACKAGE_NAME }}
        path: build/lib/${{ matrix.config }}/release.zip
